target-version = "py311"
line-length = 88
src = ["src"]

[lint]
ignore = [
    "ANN401",
    "COM812",
    "CPY001",
    "D100",
    "D101",
    "D102",
    "D103",
    "D104",
    "D105",
    "D107",
    "D203",
    "D213",
    "E501",
    "ISC001",
]
select = ["ALL"]

[lint.per-file-ignores]
"tests/*" = ["PLR2004", "S101", "S105", "SLF001"]
